### ISSUE TITLE
Feature request. Add support for React v17

### ISSUE THREAD

**Issue by markhker** [dsznajder/vscode-react-javascript-snippets#153] opened 2020-11-12 23:34 UTC
React v17 no longer needs to `import React from 'react'`
I was wondering if it is possible to update this extension.

Thanks.

**Comment by dsznajder** [comment] 2020-11-13 08:24
@markhker the problem is, that not all projects are already migrated to v17. I would like to not force most of people to migrate, I will probably make some additional alias or maybe finally find way to implement options and dynamically parse `json` files to handle semis, single / double colons etc.

**Comment by srikanth597** [comment] 2020-12-08 07:31
![autoImport](https://user-images.githubusercontent.com/32018044/101453046-b7494300-3954-11eb-8ae4-4f444cf501eb.gif)
Hi,
I don't know whether My issue also related to the latest version, whenever I try useState or useEffect snippet it is not adding it to Import Statement.
It used to work a few weeks back, I am using Auto Import Extension as well, not sure what am I doing wrong there!.
I tried all the recent React versions i.e **16.8, 16.12,....,17.0.01**
Vs Code:1.50.1
Can u let me know what I can do to fix it so that it can add automatically whenever I use this Snippets

**Comment by dsznajder** [comment] 2020-12-14 09:29
@markhker They will be with `_` prefix for current development. In future I hope I could make options for it.

@srikanth597 It's not related to package but snippets itself. Auto import does not work that way and to resolve this you should look for some solution in VSCode but I couldn't also find this.

**Comment by prospernglazi** [comment] 2022-01-19 14:55
Have you removed the _rafce for creating a functional component without importing React? I tried it today and it's not working. Thanks

**Comment by dsznajder** [comment] 2022-01-19 15:17
@prospernglazi looks like I forgot totally to apply `importReactOnTop` setting. It will be fixed in `v4.0.4` in an hour or two. Currently you won't need `_` prefix for those, just changing a setting inside your VSCode

**Comment by dsznajder** [comment] 2022-01-19 17:09
@prospernglazi released v4.0.4 Check out settings 👀

**Closed by dsznajder** 2022-01-19 17:09 UTC
Labels: feature request
