### ISSUE TITLE
UNABLE TO USE EMMETS 

### ISSUE THREAD

**Issue by Ankush-GH** [dsznajder/vscode-react-javascript-snippets#233] opened 2022-02-03 07:27 UTC
im ab unable to use emmets in my vs code ,emmets like rafce,rfce and such, i have installed es7  extenension but still im unable to resolve the problem

**Comment by dsznajder** [comment] 2022-02-03 09:55
#226 Duplicate of

**Closed by dsznajder** 2022-02-03 09:55 UTC
