### ISSUE TITLE
_rfc boiler plate

### ISSUE THREAD

**Issue by brking** [dsznajder/vscode-react-javascript-snippets#221] opened 2022-01-22 19:30 UTC
The _rfc boilerplate was working last week but not today.  Any idea why?

**Comment by MarianAct** [comment] 2022-01-22 20:13
I have the same issue, it was worked 2-3 days ago but now it stopped working...

**Comment by PabloPenia** [comment] 2022-01-22 22:24
same here, I've reinstalled yesterday and discover that snippets changed, now without unserscore, for example `_rafce` now is `rafce`. But today stop working at all. Even the search shortcut is not working. When I use CTRL + SHIFT + R I get this message:

![Captura de pantalla_2022-01-22_19-22-08](https://user-images.githubusercontent.com/88749586/150657348-4b6bcd7e-57e6-4647-8cc1-ea67f99e4a25.png)

**Comment by nizzu1102** [comment] 2022-01-23 00:13
The extension was updated, to have the same settings go back to the previous version,
The option to install another version is in the context menu. Or the gear icon for each extension.

**Comment by MarianAct** [comment] 2022-01-23 10:30
I just downgraded to version 3.1.1 and worked for me, thanks.

**Comment by dsznajder** [comment] 2022-01-23 12:07
Duplicate of #215 #220

**Closed by dsznajder** 2022-01-23 12:07 UTC

**Comment by brking** [comment] 2022-01-23 17:12
I have seen the solution.  Basically, we still use rfc (instead of _rfc), but you need to got to the settings of ES7 and uncheck the setting for 'React Snippets > Settings: Import React on Top'... or just search for 'importreactontop'
