### ISSUE TITLE
_rfc / _rfce is gone in new version

### ISSUE THREAD

**Issue by bayuprathama** [dsznajder/vscode-react-javascript-snippets#220] opened 2022-01-22 12:17 UTC
Basically it's snippet that create a react functional component without importing React at the top of the file. In the new version of the extension the snippet is no longer available

**Comment by dsznajder** [comment] 2022-01-22 12:38
Duplicate of #215. Please look at [README Options](https://github.com/dsznajder/vscode-react-javascript-snippets#options)

**Closed by dsznajder** 2022-01-22 12:39 UTC

**Comment by brking** [comment] 2022-01-23 17:09
Thank you
